language: python
python: '3.5'
sudo: false

before_install:
  - python --version

install:
  - virtualenv --version
  - easy_install --version
  - pip --version
  - pip install --use-mirrors -q mock nose PyHamcrest
  - python setup.py -q install
  
script:
  - behave android_behave --tags=dragAndDrop
  - behave android_behave --tags=StartAlarm
