language: python
python:
  - 2.6
  - 2.7
  - pypy

install:
  - pip install --use-mirrors -q mock nose PyHamcrest
  - python setup.py -q install
script:
  - python --version
  - behave --tags=dragAndDrop
  - behave --tags=StartAlarm
